# Generated by Django 5.1.1 on 2024-11-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phn_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
